### ISSUE TITLE
sync {{strategy.position_size}}

### ISSUE THREAD

**Issue by colticol** [hamtore/hamtore#4]
{{strategy.position_size}} で注文数量をコントロールすることを考えています．
- キャッシュに現在のポジション数量を保持します．
- `volume * {{strategy.position_size}} - current_position_size` を注文数量とします．

この場合，以下のような利点があります．

- ユーザは任意のタイミングでstrategyを稼働できる．
- ~~万一アラートをロストしても，次のアラートで補正される．~~ 実現方法次第

ただし，上記実現のためには以下のことが課題となっています．

- 短時間に同strategyの注文が飛んでくることを考慮すると，read/write lock をかけておく必要がある．
webhook でlockをかけることは高速並列実行ができなくなることを意味するため避けたい．
- strategyがretry tableに入っている間に次の注文が来てしまうと，両方の注文が成立した時点でポジションがずれる．
- 指値注文の場合は？

これらを考慮すると，注文が成立する前提でcacheを更新しておいて，
このcacheのread/writeの間のみロックをかける方針にするのが良いかもしれません．
=> この場合，注文ロストした場合ずれることになる．

**Comment by gevamster** [comment]
注文ロストは取引所依存の場合もあるので、はむとれの思想通り、高速並列実行よりも確実な注文を選択した方が良いと思います。

**Comment by colticol** [comment]
https://github.com/hamtore/hamtore/pull/6
position_size によるチェックを行うようにしました．
